import { useEffect, useRef, useState } from "react";
import type { EditorStatus, SeleanEditor } from "../wasm/types";

/**
 * Manages the lifecycle of the WASM-based SeleanEditor.
 *
 * Loads the WASM module and initializes the editor on the given canvas.
 * Keyboard shortcuts are handled by the parent component (App.tsx).
 *
 * @param canvasId - The HTML canvas element ID.
 */
export function useSeleanEditor(canvasId: string) {
  const editorRef = useRef<SeleanEditor | null>(null);
  const [status, setStatus] = useState<EditorStatus>("loading");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function init() {
      // Check WebGPU support
      if (!navigator.gpu) {
        setStatus("unsupported");
        return;
      }

      try {
        // Dynamic import of the WASM package (generated by wasm-pack).
        // The WASM module may not exist during type-checking, so we use
        // a dynamic import with type assertion. At runtime, wasm-pack
        // generates the correct module.
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const wasm: any = await import("../wasm/pkg/selean_wasm");
        await wasm.default();

        if (cancelled) return;

        const editor: SeleanEditor = await wasm.SeleanEditor.create(canvasId);
        editorRef.current = editor;
        setStatus("ready");
      } catch (err) {
        if (cancelled) return;
        const message = err instanceof Error ? err.message : String(err);
        setError(message);
        setStatus("error");
      }
    }

    init();

    return () => {
      cancelled = true;
    };
  }, [canvasId]);

  return { editorRef, status, error };
}
