import { useCallback, useEffect, useRef, useState } from "react";
import type { EditorStatus, SeleanEditor } from "../wasm/types";

/**
 * Manages the lifecycle of the WASM-based SeleanEditor.
 *
 * Loads the WASM module, initializes the editor on the given canvas,
 * and sets up the keyboard handler for undo/redo.
 *
 * @param canvasId - The HTML canvas element ID.
 * @param onSceneChanged - Optional callback fired after keyboard undo/redo.
 */
export function useSeleanEditor(canvasId: string, onSceneChanged?: () => void) {
  const editorRef = useRef<SeleanEditor | null>(null);
  const [status, setStatus] = useState<EditorStatus>("loading");
  const [error, setError] = useState<string | null>(null);
  const onSceneChangedRef = useRef(onSceneChanged);
  onSceneChangedRef.current = onSceneChanged;

  useEffect(() => {
    let cancelled = false;

    async function init() {
      // Check WebGPU support
      if (!navigator.gpu) {
        setStatus("unsupported");
        return;
      }

      try {
        // Dynamic import of the WASM package (generated by wasm-pack)
        const wasm = await import("../wasm/pkg/selean_wasm");
        await wasm.default();

        if (cancelled) return;

        const editor = await wasm.SeleanEditor.create(canvasId);
        editorRef.current = editor;
        setStatus("ready");
      } catch (err) {
        if (cancelled) return;
        const message = err instanceof Error ? err.message : String(err);
        setError(message);
        setStatus("error");
      }
    }

    init();

    return () => {
      cancelled = true;
    };
  }, [canvasId]);

  // Keyboard handler for undo/redo
  const handleKeyDown = useCallback((e: KeyboardEvent) => {
    const editor = editorRef.current;
    if (!editor) return;

    const isCtrlOrMeta = e.ctrlKey || e.metaKey;

    if (isCtrlOrMeta && e.key === "z" && !e.shiftKey) {
      e.preventDefault();
      editor.undo();
      onSceneChangedRef.current?.();
    } else if (
      (isCtrlOrMeta && e.key === "z" && e.shiftKey) ||
      (isCtrlOrMeta && e.key === "y")
    ) {
      e.preventDefault();
      editor.redo();
      onSceneChangedRef.current?.();
    }
  }, []);

  useEffect(() => {
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [handleKeyDown]);

  return { editorRef, status, error };
}
