/**
 * Fails fast with a clear message when the WASM bundle has not been built.
 *
 * Runs before `npm run dev` and `npm run build`. The bundle is generated by
 * wasm-pack into src/wasm/pkg/ and is not checked in.
 */
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

const pkgDir = fileURLToPath(new URL("../src/wasm/pkg/", import.meta.url));
const required = ["selean_wasm.js", "selean_wasm_bg.wasm"];
const missing = required.filter((file) => !existsSync(pkgDir + file));

if (missing.length > 0) {
  console.error(
    `WASM bundle not found (missing ${missing.join(", ")} in src/wasm/pkg/).\n` +
      "Build it first:\n\n" +
      "  npm run wasm:build\n\n" +
      "This needs wasm-pack (https://rustwasm.github.io/wasm-pack/installer/)\n" +
      "and has to be re-run after changing any Rust crate.",
  );
  process.exit(1);
}
