/// <reference types="vitest" />
import path from "node:path";
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      // Redirect the WASM package to a lightweight stub during tests.
      // The real package is generated by wasm-pack and only exists at build time.
      "../wasm/pkg/selean_wasm": path.resolve(
        __dirname,
        "src/test/wasm-stub.ts",
      ),
    },
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    globals: true,
    css: false,
  },
});
