//! CLAUDE.md generation for Claude Code export.
//!
//! Produces a markdown file containing design tokens, component inventory,
//! and project conventions extracted from a [`Document`]. This file enables
//! Claude Code to make informed edits to the generated project.

use std::fmt::Write;

use selean_engine::persistence::Document;

use crate::jsx::sanitize_component_name;
use crate::tokens::extract_tokens;

/// Generates a CLAUDE.md file for use with Claude Code.
///
/// Contains design tokens, component inventory, and project conventions
/// extracted from the [`Document`].
#[must_use]
pub fn generate_claude_md(document: &Document) -> String {
    let mut out = String::new();
    write_header(&mut out);
    write_design_tokens(&mut out, document);
    write_components(&mut out, document);
    write_conventions(&mut out);
    write_structure(&mut out, document);
    write_editing_guidelines(&mut out);
    out
}

/// Writes the top-level heading and intro blurb.
fn write_header(out: &mut String) {
    out.push_str("# Selean Export - Design System\n\n");
    out.push_str(
        "> This project was generated by Selean. The design tokens and component structure\n\
         > below reflect the visual design. Use these as the source of truth when making edits.\n\n",
    );
}

/// Writes the Design Tokens section (colors and fonts).
fn write_design_tokens(out: &mut String, document: &Document) {
    let tokens = extract_tokens(document);

    out.push_str("## Design Tokens\n\n");

    write_colors_table(out, &tokens.colors);
    write_fonts_table(out, &tokens.fonts);
}

/// Writes the colors sub-table.
fn write_colors_table(out: &mut String, colors: &[crate::tokens::TokenColor]) {
    out.push_str("### Colors\n\n");

    if colors.is_empty() {
        out.push_str("No color tokens found in the document.\n\n");
        return;
    }

    out.push_str("| Color | Hex | Usage Count |\n");
    out.push_str("|-------|-----|-------------|\n");
    for color in colors {
        // U+2588 FULL BLOCK for visual color swatch
        let _ = writeln!(
            out,
            "| \u{2588}\u{2588} | {} | {} |",
            color.hex, color.count
        );
    }
    out.push('\n');
}

/// Writes the fonts sub-table.
fn write_fonts_table(out: &mut String, fonts: &[crate::tokens::TokenFont]) {
    out.push_str("### Fonts\n\n");

    if fonts.is_empty() {
        out.push_str("No font tokens found in the document.\n\n");
        return;
    }

    out.push_str("| Family | Weights |\n");
    out.push_str("|--------|---------|\n");
    for font in fonts {
        let weights_str = font
            .weights
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "| {} | {} |", font.family, weights_str);
    }
    out.push('\n');
}

/// Writes the Components section listing pages and their dimensions.
fn write_components(out: &mut String, document: &Document) {
    out.push_str("## Components\n\n");
    out.push_str("| Component | File | Dimensions |\n");
    out.push_str("|-----------|------|------------|\n");

    for page in document.pages() {
        let name = sanitize_component_name(&page.name);
        let _ = writeln!(
            out,
            "| {} | src/components/{}.tsx | {}x{} |",
            name,
            name,
            format_dimension(page.width),
            format_dimension(page.height),
        );
    }
    out.push('\n');
}

/// Writes the Conventions section.
fn write_conventions(out: &mut String) {
    out.push_str("## Conventions\n\n");
    out.push_str("- **Framework**: React 18 + TypeScript\n");
    out.push_str("- **Styling**: Tailwind CSS v4 with arbitrary values\n");
    out.push_str("- **Build**: Vite\n");
    out.push_str("- **Layout**: Absolute positioning (design-faithful, not responsive)\n");
    out.push_str("- **Components**: One component per page, all in `src/components/`\n");
    out.push_str(
        "- **Assets**: Image references use asset IDs; replace with actual paths when deploying\n\n",
    );
}

/// Writes the Structure section showing file layout.
fn write_structure(out: &mut String, document: &Document) {
    out.push_str("## Structure\n\n");
    out.push_str("```\nsrc/\n");
    out.push_str("  main.tsx          # Entry point\n");
    out.push_str("  App.tsx           # Root component, imports all page components\n");
    out.push_str("  index.css         # Tailwind directives\n");
    out.push_str("  components/\n");

    for page in document.pages() {
        let name = sanitize_component_name(&page.name);
        let _ = writeln!(out, "    {name}.tsx");
    }

    out.push_str("```\n\n");
}

/// Writes the Editing Guidelines section.
fn write_editing_guidelines(out: &mut String) {
    out.push_str("## Editing Guidelines\n\n");
    out.push_str(
        "- Preserve absolute positioning values unless explicitly asked to make responsive\n",
    );
    out.push_str("- Color values use Tailwind arbitrary values (e.g., `bg-[#FF5733]`)\n");
    out.push_str("- Text sizes use arbitrary pixel values (e.g., `text-[24px]`)\n");
    out.push_str(
        "- When adding new elements, follow the existing pattern of absolute positioned divs\n",
    );
    out.push_str(
        "- Font families are set via arbitrary values; ensure fonts are loaded if changing\n",
    );
}

/// Formats a page dimension as a clean integer or one-decimal string.
fn format_dimension(v: f32) -> String {
    if (v - v.round()).abs() < 0.001 {
        #[allow(clippy::cast_possible_truncation)]
        return format!("{}", v.round() as i32);
    }
    format!("{v:.1}")
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use selean_common::types::NodeId;
    use selean_engine::persistence::Page;
    use selean_engine::scene::{
        BoundingBox, Color, FontStyle, SceneNode, SceneNodeKind, TextAlign,
    };

    use super::*;

    fn make_text_node(family: &str, weight: u16, text_color: Option<Color>) -> SceneNode {
        SceneNode::new(
            NodeId::new(),
            "T".to_string(),
            SceneNodeKind::Text {
                content: "text".to_string(),
                font_size: 16.0,
                font_family: family.to_string(),
                font_weight: weight,
                font_style: FontStyle::Normal,
                text_align: TextAlign::Left,
                line_height: 1.2,
                text_color,
            },
            BoundingBox::new(0.0, 0.0, 100.0, 30.0),
        )
    }

    fn make_frame_with_fill(color: Color) -> SceneNode {
        let mut node = SceneNode::new(
            NodeId::new(),
            "F".to_string(),
            SceneNodeKind::Frame {
                corner_radius: [0.0; 4],
            },
            BoundingBox::new(0.0, 0.0, 100.0, 100.0),
        );
        node.fill = Some(color);
        node
    }

    #[test]
    fn empty_document_produces_valid_md() {
        let doc = Document::new();
        let md = generate_claude_md(&doc);
        assert!(md.contains("# Selean Export - Design System"));
        assert!(md.contains("## Design Tokens"));
        assert!(md.contains("## Components"));
        assert!(md.contains("## Conventions"));
        assert!(md.contains("## Structure"));
        assert!(md.contains("## Editing Guidelines"));
    }

    #[test]
    fn colors_section_lists_tokens() {
        let mut page = Page::new("P1", 800.0, 600.0);
        let red = Color::new(1.0, 0.0, 0.0, 1.0);
        page.scene.add_root(make_frame_with_fill(red));
        page.scene.add_root(make_frame_with_fill(red));

        let doc = Document::from_pages(vec![page]);
        let md = generate_claude_md(&doc);

        assert!(md.contains("#ff0000"));
        assert!(md.contains("| 2 |"));
    }

    #[test]
    fn fonts_section_lists_families() {
        let mut page = Page::new("P1", 800.0, 600.0);
        page.scene.add_root(make_text_node("Inter", 400, None));
        page.scene.add_root(make_text_node("Inter", 700, None));
        page.scene.add_root(make_text_node("Roboto", 400, None));

        let doc = Document::from_pages(vec![page]);
        let md = generate_claude_md(&doc);

        assert!(md.contains("| Inter | 400, 700 |"));
        assert!(md.contains("| Roboto | 400 |"));
    }

    #[test]
    fn components_section_lists_pages() {
        let pages = vec![
            Page::new("Home", 1920.0, 1080.0),
            Page::new("About", 1280.0, 720.0),
        ];
        let doc = Document::from_pages(pages);
        let md = generate_claude_md(&doc);

        assert!(md.contains("| Home |"));
        assert!(md.contains("| About |"));
    }

    #[test]
    fn page_dimensions_shown() {
        let pages = vec![
            Page::new("Wide", 1920.0, 1080.0),
            Page::new("Small", 800.0, 600.0),
        ];
        let doc = Document::from_pages(pages);
        let md = generate_claude_md(&doc);

        assert!(md.contains("1920x1080"));
        assert!(md.contains("800x600"));
    }

    #[test]
    fn conventions_section_present() {
        let doc = Document::new();
        let md = generate_claude_md(&doc);
        assert!(md.contains("Tailwind CSS"));
        assert!(md.contains("React"));
    }

    #[test]
    fn structure_section_present() {
        let doc = Document::new();
        let md = generate_claude_md(&doc);
        assert!(md.contains("main.tsx"));
        assert!(md.contains("App.tsx"));
        assert!(md.contains("index.css"));
        assert!(md.contains("components/"));
    }

    #[test]
    fn editing_guidelines_present() {
        let doc = Document::new();
        let md = generate_claude_md(&doc);
        assert!(md.contains("## Editing Guidelines"));
        assert!(md.contains("absolute positioning"));
        assert!(md.contains("bg-[#FF5733]"));
    }

    #[test]
    fn structure_lists_page_component_files() {
        let pages = vec![
            Page::new("Landing", 1920.0, 1080.0),
            Page::new("Pricing", 1280.0, 720.0),
        ];
        let doc = Document::from_pages(pages);
        let md = generate_claude_md(&doc);

        assert!(md.contains("Landing.tsx"));
        assert!(md.contains("Pricing.tsx"));
    }

    #[test]
    fn empty_tokens_show_fallback_text() {
        let doc = Document::new();
        let md = generate_claude_md(&doc);
        assert!(md.contains("No color tokens found"));
        assert!(md.contains("No font tokens found"));
    }
}
